//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestTracker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestTracker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Checked.
        /// </summary>
        internal static string CompleteChecked {
            get {
                return ResourceManager.GetString("CompleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last Completed: .
        /// </summary>
        internal static string DateLastCompleted {
            get {
                return ResourceManager.GetString("DateLastCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Started: .
        /// </summary>
        internal static string DateStarted {
            get {
                return ResourceManager.GetString("DateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Quests.
        /// </summary>
        internal static string DefaultQuestTabName {
            get {
                return ResourceManager.GetString("DefaultQuestTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Checked.
        /// </summary>
        internal static string DeleteChecked {
            get {
                return ResourceManager.GetString("DeleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate....
        /// </summary>
        internal static string DonateLink {
            get {
                return ResourceManager.GetString("DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Export.
        /// </summary>
        internal static string ExportCommand {
            get {
                return ResourceManager.GetString("ExportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file to Export.
        /// </summary>
        internal static string ExportFileTitle {
            get {
                return ResourceManager.GetString("ExportFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import.
        /// </summary>
        internal static string ImportCommand {
            get {
                return ResourceManager.GetString("ImportCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File to Import.
        /// </summary>
        internal static string ImportFileTitle {
            get {
                return ResourceManager.GetString("ImportFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed.
        /// </summary>
        internal static string NotCompleted {
            get {
                return ResourceManager.GetString("NotCompleted", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon QuestTracker {
            get {
                object obj = ResourceManager.GetObject("QuestTracker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestTracker.
        /// </summary>
        internal static string QuestTrackerTitle {
            get {
                return ResourceManager.GetString("QuestTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuestTracker Website.
        /// </summary>
        internal static string QuestTrackerWebsiteLink {
            get {
                return ResourceManager.GetString("QuestTrackerWebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Completed Quests.
        /// </summary>
        internal static string ShowCompleted {
            get {
                return ResourceManager.GetString("ShowCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomplete.
        /// </summary>
        internal static string Uncomplete {
            get {
                return ResourceManager.GetString("Uncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncomplete Checked.
        /// </summary>
        internal static string UncompleteChecked {
            get {
                return ResourceManager.GetString("UncompleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        internal static string XmlFiles {
            get {
                return ResourceManager.GetString("XmlFiles", resourceCulture);
            }
        }
    }
}
